services:
  - type: web
    name: flask-backend
    runtime: python
    buildCommand: ""
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
